name: tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        numpy-version: ['1.24.4', '1.25.2', '1.26.4', '2.0.2', '2.1.3', '2.2.0']
        exclude:
        - numpy-version: '1.24.4'
          python-version: '3.12'
        - numpy-version: '1.24.4'
          python-version: '3.13'

        - numpy-version: '1.25.2'
          python-version: '3.12'
        - numpy-version: '1.25.2'
          python-version: '3.13'

        - numpy-version: '1.26.4'
          python-version: '3.13'

        - numpy-version: '2.0.2'
          python-version: '3.13'

        - numpy-version: '2.1.3'
          python-version: '3.9'

        - numpy-version: '2.2.0'
          python-version: '3.9'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
        python -m pip install scipy
    - name: Install scarff
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest

  no-scipy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13']
        numpy-version: ['1.25.2', '1.26.4', '2.0.2', '2.1.3', '2.2.0']
        exclude:
        - numpy-version: '1.25.2'
          python-version: '3.12'
        - numpy-version: '1.25.2'
          python-version: '3.13'

        - numpy-version: '1.26.4'
          python-version: '3.13'

        - numpy-version: '2.0.2'
          python-version: '3.13'

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install pytest
        python -m pip install numpy==${{ matrix.numpy-version }}
    - name: Install scarff
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        python -m pytest
